#!/usr/bin/env python3
"""bin2c.py IN OUT NAME -- emit a binary file as a const uint8_t C array."""
import sys

src, dst, name = sys.argv[1:4]
data = open(src, 'rb').read()
with open(dst, 'w') as f:
    f.write('/* generated by tools/bin2c.py from %s -- do not edit */\n' % src.split('/')[-1])
    f.write('#pragma once\n#include <stdint.h>\n')
    f.write('static const uint8_t %s[%d] = {\n' % (name, len(data)))
    for i in range(0, len(data), 16):
        f.write('\t' + ','.join('0x%02x' % b for b in data[i:i+16]) + ',\n')
    f.write('};\n')
