#!/usr/bin/env python3
"""gen_rules.py -- build tts/rules_nrl.c and tts/rules_cts.c from the reference tables.

Rule string format used by tts/rules.c:   LEFT[MATCH]RIGHT=OUTPUT
  ' ' in LEFT/RIGHT is a word boundary (CTS '<' is converted to ' ').
  NRL output is a Wasser phoneme string; CTS output is allophone names.
Groups: 0 punctuation/other, 1..26 = A..Z, 27 = apostrophe, 28 = digits.
"""
import re, sys, os

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def group_of(c):
    if 'A' <= c <= 'Z': return ord(c) - 64
    if c == "'": return 27
    if '0' <= c <= '9': return 28
    return 0

def emit_c(path, name, groups, header):
    with open(path, 'w') as f:
        f.write('/* generated by tools/gen_rules.py -- do not edit */\n')
        f.write(header)
        f.write('#include <stddef.h>\n#include "rules.h"\n\n')
        for g in range(29):
            f.write('static const char *const g%d[] = {\n' % g)
            for r in groups[g]:
                f.write('\t"%s",\n' % r.replace('\\', '\\\\').replace('"', '\\"'))
            f.write('\tNULL\n};\n')
        f.write('\nstatic const char *const *const groups[29] = {\n\t' +
                ', '.join('g%d' % g for g in range(29)) + '\n};\n\n')
        f.write('const rule_table_t %s = { groups };\n' % name)
    print(path, sum(len(g) for g in groups), 'rules')

# ---------------------------------------------------------------- NRL / Wasser
src = open(os.path.join(root, 'reference/wasser-eng2phon/english.c')).read()
groups = [[] for _ in range(29)]
sym = {'Anything': '', 'Nothing': ' ', 'Pause': ' ', 'Silent': ''}
def val(tok):
    tok = tok.strip()
    if tok in sym: return sym[tok]
    if tok == '0': return None
    assert tok.startswith('"') and tok.endswith('"'), tok
    return tok[1:-1]
for m in re.finditer(r'^\s*\{\s*(Anything|Nothing|"[^"]*"),\s*("[^"]*"|0),\s*(Anything|Nothing|"[^"]*"),\s*(Pause|Silent|"[^"]*")\s*\}', src, re.M):
    left, match, right, out = (val(x) for x in m.groups())
    if match is None: continue          # end-of-table sentinel
    groups[group_of(match[0])].append('%s[%s]%s=%s' % (left, match, right, out))
emit_c(os.path.join(root, 'tts/rules_nrl.c'), 'rules_nrl', groups,
       '/* NRL letter-to-sound rules as coded by John A. Wasser (1985, public domain). */\n')

# ---------------------------------------------------------------- CTS256A-AL2
src = open(os.path.join(root, 'reference/cts256/RULES.TXT')).read()
groups = [[] for _ in range(29)]
n = 0
for m in re.finditer(r'^[0-9A-F]{4}:\t(.*?)\[(.*?)\](.*?) = \[(.*?)\]', src, re.M):
    left, match, right, out = m.groups()
    left = left.replace('<', ' '); right = right.replace('<', ' ')
    g = group_of(match[0]) if match else 0
    groups[g].append('%s[%s]%s=%s' % (left, match, right, out))
    n += 1
assert n == 432, n
emit_c(os.path.join(root, 'tts/rules_cts.c'), 'rules_cts', groups,
       '/* CTS256A-AL2 text-to-allophone rules, extracted from the ROM by Michel Bernard (GmEsoft, GPL-3.0). */\n')
