/* generated by tools/gen_rules.py -- do not edit */
/* NRL letter-to-sound rules as coded by John A. Wasser (1985, public domain). */
#include <stddef.h>
#include "rules.h"

static const char *const g0[] = {
	"[ ]= ",
	"[-]=",
	"[,]= ",
	"[.]= ",
	"[?]= ",
	"[!]= ",
	NULL
};
static const char *const g1[] = {
	"[A] =AX",
	" [ARE] =AAr",
	" [AR]O=AXr",
	"[AR]#=EHr",
	"^[AS]#=EYs",
	"[A]WA=AX",
	"[AW]=AO",
	" :[ANY]=EHnIY",
	"[A]^+#=EY",
	"#:[ALLY]=AXlIY",
	" [AL]#=AXl",
	"[AGAIN]=AXgEHn",
	"#:[AG]E=IHj",
	"[A]^+:#=AE",
	" :[A]^+ =EY",
	"[A]^%=EY",
	" [ARR]=AXr",
	"[ARR]=AEr",
	" :[AR] =AAr",
	"[AR] =ER",
	"[AR]=AAr",
	"[AIR]=EHr",
	"[AI]=EY",
	"[AY]=EY",
	"[AU]=AO",
	"#:[AL] =AXl",
	"#:[ALS] =AXlz",
	"[ALK]=AOk",
	"[AL]^=AOl",
	" :[ABLE]=EYbAXl",
	"[ABLE]=AXbAXl",
	"[ANG]+=EYnj",
	"[A]=AE",
	NULL
};
static const char *const g2[] = {
	" [BE]^#=bIH",
	"[BEING]=bIYIHNG",
	" [BOTH] =bOWTH",
	" [BUS]#=bIHz",
	"[BUIL]=bIHl",
	"[B]=b",
	NULL
};
static const char *const g3[] = {
	" [CH]^=k",
	"^E[CH]=k",
	"[CH]=CH",
	" S[CI]#=sAY",
	"[CI]A=SH",
	"[CI]O=SH",
	"[CI]EN=SH",
	"[C]+=s",
	"[CK]=k",
	"[COM]%=kAHm",
	"[C]=k",
	NULL
};
static const char *const g4[] = {
	"#:[DED] =dIHd",
	".E[D] =d",
	"#:^E[D] =t",
	" [DE]^#=dIH",
	" [DO] =dUW",
	" [DOES]=dAHz",
	" [DOING]=dUWIHNG",
	" [DOW]=dAW",
	"[DU]A=jUW",
	"[D]=d",
	NULL
};
static const char *const g5[] = {
	"#:[E] =",
	"':^[E] =",
	" :[E] =IY",
	"#[ED] =d",
	"#:[E]D =",
	"[EV]ER=EHv",
	"[E]^%=IY",
	"[ERI]#=IYrIY",
	"[ERI]=EHrIH",
	"#:[ER]#=ER",
	"[ER]#=EHr",
	"[ER]=ER",
	" [EVEN]=IYvEHn",
	"#:[E]W=",
	"T[EW]=UW",
	"S[EW]=UW",
	"R[EW]=UW",
	"D[EW]=UW",
	"L[EW]=UW",
	"Z[EW]=UW",
	"N[EW]=UW",
	"J[EW]=UW",
	"TH[EW]=UW",
	"CH[EW]=UW",
	"SH[EW]=UW",
	"[EW]=yUW",
	"[E]O=IY",
	"#:S[ES] =IHz",
	"#:C[ES] =IHz",
	"#:G[ES] =IHz",
	"#:Z[ES] =IHz",
	"#:X[ES] =IHz",
	"#:J[ES] =IHz",
	"#:CH[ES] =IHz",
	"#:SH[ES] =IHz",
	"#:[E]S =",
	"#:[ELY] =lIY",
	"#:[EMENT]=mEHnt",
	"[EFUL]=fUHl",
	"[EE]=IY",
	"[EARN]=ERn",
	" [EAR]^=ER",
	"[EAD]=EHd",
	"#:[EA] =IYAX",
	"[EA]SU=EH",
	"[EA]=IY",
	"[EIGH]=EY",
	"[EI]=IY",
	" [EYE]=AY",
	"[EY]=IY",
	"[EU]=yUW",
	"[E]=EH",
	NULL
};
static const char *const g6[] = {
	"[FUL]=fUHl",
	"[F]=f",
	NULL
};
static const char *const g7[] = {
	"[GIV]=gIHv",
	" [G]I^=g",
	"[GE]T=gEH",
	"SU[GGES]=gjEHs",
	"[GG]=g",
	" B#[G]=g",
	"[G]+=j",
	"[GREAT]=grEYt",
	"#[GH]=",
	"[G]=g",
	NULL
};
static const char *const g8[] = {
	" [HAV]=hAEv",
	" [HERE]=hIYr",
	" [HOUR]=AWER",
	"[HOW]=hAW",
	"[H]#=h",
	"[H]=",
	NULL
};
static const char *const g9[] = {
	" [IN]=IHn",
	" [I] =AY",
	"[IN]D=AYn",
	"[IER]=IYER",
	"#:R[IED]=IYd",
	"[IED] =AYd",
	"[IEN]=IYEHn",
	"[IE]T=AYEH",
	" :[I]%=AY",
	"[I]%=IY",
	"[IE]=IY",
	"[I]^+:#=IH",
	"[IR]#=AYr",
	"[IZ]%=AYz",
	"[IS]%=AYz",
	"[I]D%=AY",
	"+^[I]^+=IH",
	"[I]T%=AY",
	"#:^[I]^+=IH",
	"[I]^+=AY",
	"[IR]=ER",
	"[IGH]=AY",
	"[ILD]=AYld",
	"[IGN] =AYn",
	"[IGN]^=AYn",
	"[IGN]%=AYn",
	"[IQUE]=IYk",
	"[I]=IH",
	NULL
};
static const char *const g10[] = {
	"[J]=j",
	NULL
};
static const char *const g11[] = {
	" [K]N=",
	"[K]=k",
	NULL
};
static const char *const g12[] = {
	"[LO]C#=lOW",
	"L[L]=",
	"#:^[L]%=AXl",
	"[LEAD]=lIYd",
	"[L]=l",
	NULL
};
static const char *const g13[] = {
	"[MOV]=mUWv",
	"[M]=m",
	NULL
};
static const char *const g14[] = {
	"E[NG]+=nj",
	"[NG]R=NGg",
	"[NG]#=NGg",
	"[NGL]%=NGgAXl",
	"[NG]=NG",
	"[NK]=NGk",
	" [NOW] =nAW",
	"[N]=n",
	NULL
};
static const char *const g15[] = {
	"[OF] =AXv",
	"[OROUGH]=EROW",
	"#:[OR] =ER",
	"#:[ORS] =ERz",
	"[OR]=AOr",
	" [ONE]=wAHn",
	"[OW]=OW",
	" [OVER]=OWvER",
	"[OV]=AHv",
	"[O]^%=OW",
	"[O]^EN=OW",
	"[O]^I#=OW",
	"[OL]D=OWl",
	"[OUGHT]=AOt",
	"[OUGH]=AHf",
	" [OU]=AW",
	"H[OU]S#=AW",
	"[OUS]=AXs",
	"[OUR]=AOr",
	"[OULD]=UHd",
	"^[OU]^L=AH",
	"[OUP]=UWp",
	"[OU]=AW",
	"[OY]=OY",
	"[OING]=OWIHNG",
	"[OI]=OY",
	"[OOR]=AOr",
	"[OOK]=UHk",
	"[OOD]=UHd",
	"[OO]=UW",
	"[O]E=OW",
	"[O] =OW",
	"[OA]=OW",
	" [ONLY]=OWnlIY",
	" [ONCE]=wAHns",
	"[ON'T]=OWnt",
	"C[O]N=AA",
	"[O]NG=AO",
	" :^[O]N=AH",
	"I[ON]=AXn",
	"#:[ON] =AXn",
	"#^[ON]=AXn",
	"[O]ST =OW",
	"[OF]^=AOf",
	"[OTHER]=AHDHER",
	"[OSS] =AOs",
	"#:^[OM]=AHm",
	"[O]=AA",
	NULL
};
static const char *const g16[] = {
	"[PH]=f",
	"[PEOP]=pIYp",
	"[POW]=pAW",
	"[PUT] =pUHt",
	"[P]=p",
	NULL
};
static const char *const g17[] = {
	"[QUAR]=kwAOr",
	"[QU]=kw",
	"[Q]=k",
	NULL
};
static const char *const g18[] = {
	" [RE]^#=rIY",
	"[R]=r",
	NULL
};
static const char *const g19[] = {
	"[SH]=SH",
	"#[SION]=ZHAXn",
	"[SOME]=sAHm",
	"#[SUR]#=ZHER",
	"[SUR]#=SHER",
	"#[SU]#=ZHUW",
	"#[SSU]#=SHUW",
	"#[SED] =zd",
	"#[S]#=z",
	"[SAID]=sEHd",
	"^[SION]=SHAXn",
	"[S]S=",
	".[S] =z",
	"#:.E[S] =z",
	"#:^##[S] =z",
	"#:^#[S] =s",
	"U[S] =s",
	" :#[S] =z",
	" [SCH]=sk",
	"[S]C+=",
	"#[SM]=zm",
	"#[SN]'=zAXn",
	"[S]=s",
	NULL
};
static const char *const g20[] = {
	" [THE] =DHAX",
	"[TO] =tUW",
	"[THAT] =DHAEt",
	" [THIS] =DHIHs",
	" [THEY]=DHEY",
	" [THERE]=DHEHr",
	"[THER]=DHER",
	"[THEIR]=DHEHr",
	" [THAN] =DHAEn",
	" [THEM] =DHEHm",
	"[THESE] =DHIYz",
	" [THEN]=DHEHn",
	"[THROUGH]=THrUW",
	"[THOSE]=DHOWz",
	"[THOUGH] =DHOW",
	" [THUS]=DHAHs",
	"[TH]=TH",
	"#:[TED] =tIHd",
	"S[TI]#N=CH",
	"[TI]O=SH",
	"[TI]A=SH",
	"[TIEN]=SHAXn",
	"[TUR]#=CHER",
	"[TU]A=CHUW",
	" [TWO]=tUW",
	"[T]=t",
	NULL
};
static const char *const g21[] = {
	" [UN]I=yUWn",
	" [UN]=AHn",
	" [UPON]=AXpAOn",
	"T[UR]#=UHr",
	"S[UR]#=UHr",
	"R[UR]#=UHr",
	"D[UR]#=UHr",
	"L[UR]#=UHr",
	"Z[UR]#=UHr",
	"N[UR]#=UHr",
	"J[UR]#=UHr",
	"TH[UR]#=UHr",
	"CH[UR]#=UHr",
	"SH[UR]#=UHr",
	"[UR]#=yUHr",
	"[UR]=ER",
	"[U]^ =AH",
	"[U]^^=AH",
	"[UY]=AY",
	" G[U]#=",
	"G[U]%=",
	"G[U]#=w",
	"#N[U]=yUW",
	"T[U]=UW",
	"S[U]=UW",
	"R[U]=UW",
	"D[U]=UW",
	"L[U]=UW",
	"Z[U]=UW",
	"N[U]=UW",
	"J[U]=UW",
	"TH[U]=UW",
	"CH[U]=UW",
	"SH[U]=UW",
	"[U]=yUW",
	NULL
};
static const char *const g22[] = {
	"[VIEW]=vyUW",
	"[V]=v",
	NULL
};
static const char *const g23[] = {
	" [WERE]=wER",
	"[WA]S=wAA",
	"[WA]T=wAA",
	"[WHERE]=WHEHr",
	"[WHAT]=WHAAt",
	"[WHOL]=hOWl",
	"[WHO]=hUW",
	"[WH]=WH",
	"[WAR]=wAOr",
	"[WOR]^=wER",
	"[WR]=r",
	"[W]=w",
	NULL
};
static const char *const g24[] = {
	"[X]=ks",
	NULL
};
static const char *const g25[] = {
	"[YOUNG]=yAHNG",
	" [YOU]=yUW",
	" [YES]=yEHs",
	" [Y]=y",
	"#:^[Y] =IY",
	"#:^[Y]I=IY",
	" :[Y] =AY",
	" :[Y]#=AY",
	" :[Y]^+:#=IH",
	" :[Y]^#=AY",
	"[Y]=IH",
	NULL
};
static const char *const g26[] = {
	"[Z]=z",
	NULL
};
static const char *const g27[] = {
	".['S]=z",
	"#:.E['S]=z",
	"#['S]=z",
	"[']=",
	NULL
};
static const char *const g28[] = {
	NULL
};

static const char *const *const groups[29] = {
	g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14, g15, g16, g17, g18, g19, g20, g21, g22, g23, g24, g25, g26, g27, g28
};

const rule_table_t rules_nrl = { groups };
